SPECIFIC_AREA = [
    {"id": "01_it", "region": "地中海地域", "specific_area": "イタリア料理", "country_code": "IT", "lang_code": "it"},
    {"id": "01_es", "region": "地中海地域", "specific_area": "スペイン料理", "country_code": "ES", "lang_code": "es"},
    {"id": "01_fr", "region": "地中海地域", "specific_area": "南フランス料理", "country_code": "FR", "lang_code": "fr"},
    {"id": "01_ma", "region": "地中海地域", "specific_area": "マグレブ料理", "country_code": "MA/DZ/TN", "lang_code": "ar"},
    {"id": "01_hr", "region": "地中海地域", "specific_area": "クロアティア料理", "country_code": "HR", "lang_code": "hr"},
    {"id": "01_gr", "region": "地中海地域", "specific_area": "ギリシャ料理", "country_code": "GR", "lang_code": "el"},
    {"id": "01_lb", "region": "地中海地域", "specific_area": "レヴァント料理", "country_code": "LB/SY/JO/PS", "lang_code": "ar"},
    {"id": "01_cy", "region": "地中海地域", "specific_area": "キプロス料理", "country_code": "CY", "lang_code": "el"},

    {"id": "02_eg", "region": "中東地域", "specific_area": "エジプト料理", "country_code": "EG", "lang_code": "ar"},
    {"id": "02_tr", "region": "中東地域", "specific_area": "アナトリア料理", "country_code": "TR", "lang_code": "tr"},
    {"id": "02_sa", "region": "中東地域", "specific_area": "ハリージ料理", "country_code": "SA/AE/BH/QA/OM/KW", "lang_code": "ar"},
    {"id": "02_iq", "region": "中東地域", "specific_area": "メソポタミア料理", "country_code": "IQ", "lang_code": "ar"},
    {"id": "02_ir", "region": "中東地域", "specific_area": "ペルシャ料理", "country_code": "IR", "lang_code": "fa"},

    {"id": "03_pk", "region": "南アジア", "specific_area": "パキスタン料理", "country_code": "PK", "lang_code": "ur"},
    {"id": "03_in1", "region": "南アジア", "specific_area": "北インド料理", "country_code": "IN", "lang_code": "hi"},
    {"id": "03_in2", "region": "南アジア", "specific_area": "南インド料理", "country_code": "IN", "lang_code": "ta"},
    {"id": "03_in3", "region": "南アジア", "specific_area": "インド・アッサム料理", "country_code": "IN", "lang_code": "as"},
    {"id": "03_bd", "region": "南アジア", "specific_area": "バングラディシュ料理", "country_code": "BD", "lang_code": "bn"},
    {"id": "03_np", "region": "南アジア", "specific_area": "ネパール料理", "country_code": "NP", "lang_code": "ne"},
    {"id": "03_bt", "region": "南アジア", "specific_area": "ブータン料理", "country_code": "BT", "lang_code": "dz, en"},
    {"id": "03_lk", "region": "南アジア", "specific_area": "スリランカ料理", "country_code": "LK", "lang_code": "si"},

    {"id": "04_mm", "region": "東南アジア", "specific_area": "ミャンマー料理", "country_code": "MM", "lang_code": "my"},
    {"id": "04_th", "region": "東南アジア", "specific_area": "タイ料理", "country_code": "TH", "lang_code": "th"},
    {"id": "04_la", "region": "東南アジア", "specific_area": "ラオス料理", "country_code": "LA", "lang_code": "lo"},
    {"id": "04_kh", "region": "東南アジア", "specific_area": "カンボジア料理", "country_code": "KH", "lang_code": "km"},
    {"id": "04_vn", "region": "東南アジア", "specific_area": "ベトナム料理", "country_code": "VN", "lang_code": "vi"},
    {"id": "04_my", "region": "東南アジア", "specific_area": "マレー料理", "country_code": "MY", "lang_code": "ms"},
    {"id": "04_id1", "region": "東南アジア", "specific_area": "ジャワ料理", "country_code": "ID", "lang_code": "jv, id"},
    {"id": "04_id2", "region": "東南アジア", "specific_area": "スンダ料理", "country_code": "ID", "lang_code": "su, id"},
    {"id": "04_id3", "region": "東南アジア", "specific_area": "バリ料理", "country_code": "ID", "lang_code": "ban, id"},
    {"id": "04_id4", "region": "東南アジア", "specific_area": "パダン料理", "country_code": "ID", "lang_code": "min, id"},
    {"id": "04_ph", "region": "東南アジア", "specific_area": "フィリピン料理", "country_code": "PH", "lang_code": "tl"},

    {"id": "05_ch1", "region": "東アジア", "specific_area": "中国・山東料理", "country_code": "CN", "lang_code": "zh"},
    {"id": "05_ch2", "region": "東アジア", "specific_area": "中国・江蘇料理", "country_code": "CN", "lang_code": "zh"},
    {"id": "05_ch3", "region": "東アジア", "specific_area": "中国・広東料理", "country_code": "CN", "lang_code": "zh"},
    {"id": "05_ch4", "region": "東アジア", "specific_area": "中国・四川料理", "country_code": "CN", "lang_code": "zh"},
    {"id": "05_ch5", "region": "東アジア", "specific_area": "中国・雲南料理", "country_code": "CN", "lang_code": "zh"},
    {"id": "05_tw", "region": "東アジア", "specific_area": "台湾料理", "country_code": "TW", "lang_code": "zh"},
    {"id": "05_kr", "region": "東アジア", "specific_area": "韓国料理", "country_code": "KR", "lang_code": "ko"},
    {"id": "06_jp", "region": "日本", "specific_area": "日本料理", "country_code": "JP", "lang_code": "ja"},
    {"id": "06_jp47", "region": "日本", "specific_area": "沖縄の料理", "country_code": "JP", "lang_code": "ja"}
]